FROM networkboot/dhcpd:latest

# let docker know how to test container health
HEALTHCHECK CMD if [ $(ps aux | grep -c -e '/usr/sbin/dhcpd') -ne 5 ] ; then exit 1; else exit 0; fi;

# Keep default entrypoint
ENTRYPOINT ["/entrypoint.sh"]