build-dhcp:
  # Use the official docker image.
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
  script:
    - cd images
    - docker build --pull -t "atlasplatform/dhcp:latest" ./dhcp
    - docker push "atlasplatform/dhcp:latest"

build-freeipa:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
  script:
    - cd images
    - docker build --pull -t "atlasplatform/freeipa-server:latest" ./freeipa
    - docker push "atlasplatform/freeipa-server:latest"

build-httpd:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
  script:
    - cd images
    - docker build --pull -t "atlasplatform/httpd:latest" ./httpd
    - docker push "atlasplatform/httpd:latest"

build-ntp:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
  script:
    - cd images
    - docker build --pull -t "atlasplatform/ntp-isolated:latest" ./ntp-isolated
    - docker push "atlasplatform/ntp-isolated:latest"

build-socat:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
  script:
    - cd images
    - docker build --pull -t "atlasplatform/socat-ansible:latest" ./socat-ansible
    - docker push "atlasplatform/socat-ansible:latest"

build-tftp:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
  script:
    - cd images
    - docker build --pull -t "atlasplatform/tftp-hpa:latest" ./tftp
    - docker push "atlasplatform/tftp-hpa:latest"