version: "3.8"
services:
  ipa:
    image: freeipa/freeipa-server:centos-8
    networks: 
      dockernet:
        ipv4_address: 172.18.0.10
      xpi:
        ipv4_address: 139.241.255.10
    mac_address: ee:ee:ee:ee:ee:e0
    hostname: ipa.cspts.xpi
    tty: true
    stdin_open: true
    read_only: false
    volumes: 
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /var/lib/ipa-data:/data:Z
    sysctls:
      net.ipv6.conf.all.disable_ipv6: 0
    command: --unattended
    environment: 
      IPA_SERVER_INSTALL_OPTS: >
        --ds-password=example123 
        --admin-password=example123 
        --domain=cspts.xpi 
        --realm=cspts.xpi 
        --setup-dns 
        --forwarder=8.8.8.8  
        --forwarder=8.8.4.4
        --ntp-server=172.18.0.11
      IPA_SERVER_HOSTNAME: ipa.cspts.xpi
  ntp:
    image: atlasplatform/ntp-isolated:latest
    networks: 
      dockernet:
        ipv4_address: 172.18.0.11
      xpi:
        ipv4_address: 139.241.255.11
    mac_address: ee:ee:ee:ee:ee:e1
    hostname: ntp.cspts.xpi
  dhcp:
    image: networkboot/dhcpd:latest
    volumes:
      - ./pxe/data/:/data
    mac_address: ee:ee:ee:ee:ee:e2
    networks: 
      dockernet:
      testnet:
        ipv4_address: 139.241.255.2
  tftp:
    image: jumanjiman/tftp-hpa:latest
    volumes:
      - ./pxe/tftpboot/boot:/tftpboot/boot
      - ./pxe/tftpboot/grub:/tftpboot/grub
      - ./pxe/tftpboot/init:/tftpboot/init
    mac_address: ee:ee:ee:ee:ee:e3
    networks: 
      dockernet:
      testnet:
        ipv4_address: 139.241.255.3
  http:
    image: httpd:latest
    mac_address: ee:ee:ee:ee:ee:e4
    volumes:
      - ./pxe/httpd/content/:/usr/local/apache2/htdocs/
      - ./pxe/httpd/httpd.conf:/usr/local/apache2/conf/httpd.conf
    ports:
      - 80:80
    networks: 
      dockernet:
      testnet:
        ipv4_address: 139.241.255.4
  ansible: 
    image: atlasplatform/socat-ansible:latest
    environment:
      SSH_PASSWORD: TODO
    mac_address: ee:ee:ee:ee:ee:e5
    networks: 
      dockernet:
      testnet:
        ipv4_address: 139.241.255.5


networks:
  dockernet:
    ipam:
      config:
        - subnet: 172.18.0.0/16
          gateway: 172.18.0.1
          ip_range: 172.18.0.0/16
  xpi:
    driver: macvlan
    driver_opts:
      parent: enp1s0
    ipam:
      config:
        - subnet: 139.241.255.0/24
          gateway: 139.241.255.1
          ip_range: 139.241.255.0/28
