version: "3.8"
services:
  ipa:
    cap_add:
      - NET_ADMIN
    image: atlasplatform/freeipa-server:latest
    restart: always
    networks: 
    #dockernet:
    #ipv4_address: 172.18.0.10
      xpi:
        ipv4_address: 192.168.1.10
    mac_address: ee:ee:ee:ee:ee:e0
    hostname: ipa.cspts.xpi
    tty: true
    stdin_open: true
    read_only: false
    volumes: 
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /var/lib/ipa-data:/data:Z
    sysctls:
      net.ipv6.conf.all.disable_ipv6: 0
    command: --unattended
    environment: 
      IPA_SERVER_INSTALL_OPTS: >
        --ds-password=example123 
        --admin-password=example123 
        --domain=cspts.xpi 
        --realm=cspts.xpi 
        --setup-dns 
        --forwarder=8.8.8.8  
        --forwarder=8.8.4.4
        --ntp-server=172.18.0.11
        --ip-address=192.168.1.10
      IPA_SERVER_HOSTNAME: ipa.cspts.xpi
      LOG4J_FORMAT_MSG_NO_LOOKUPS: "true"
  ntp:
    image: atlasplatform/ntp-isolated:latest
    restart: always
    networks: 
      dockernet:
        ipv4_address: 172.18.0.11
      xpi:
        ipv4_address: 192.168.1.11
    mac_address: ee:ee:ee:ee:ee:e1
    hostname: ntp.cspts.xpi
  dhcp:
    image: atlasplatform/dhcp:latest
    restart: always
    volumes:
      - ./pxe/data/:/data
    mac_address: ee:ee:ee:ee:ee:e2
    networks: 
      dockernet:
      xpi:
        ipv4_address: 192.168.1.2
  tftp:
    image: atlasplatform/tftp-hpa:latest
    restart: always
    volumes:
      - ./pxe/tftpboot/boot:/tftpboot/boot
      - ./pxe/tftpboot/grub:/tftpboot/grub
      - ./pxe/tftpboot/init:/tftpboot/init
    mac_address: ee:ee:ee:ee:ee:e3
    networks: 
      dockernet:
      xpi:
        ipv4_address: 192.168.1.3
  http:
    image: atlasplatform/httpd:latest
    restart: always
    mac_address: ee:ee:ee:ee:ee:e4
    volumes:
      - ./pxe/httpd/content/:/usr/local/apache2/htdocs/
      - ./pxe/httpd/httpd.conf:/usr/local/apache2/conf/httpd.conf
    environment: 
      LOG4J_FORMAT_MSG_NO_LOOKUPS: "true"
    networks: 
      dockernet:
      xpi:
        ipv4_address: 192.168.1.4
  ansible: 
    image: atlasplatform/socat-ansible:latest
    restart: always
    environment:
      SSH_PASSWORD: TODO
    mac_address: ee:ee:ee:ee:ee:e5
    networks: 
      dockernet:
      xpi:
        ipv4_address: 192.168.1.5
  gitlab:
    image: 'gitlab/gitlab-ee:latest'
    restart: always
    hostname: 'gitlab.cspts.xpi'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.cspts.xpi'
        letsencrypt['enable'] = false
        # Add any other gitlab.rb configuration here, each on its own line
        gitlab_rails['ldap_enabled'] = true
        gitlab_rails['prevent_ldap_sign_in'] = false
        gitlab_rails['ldap_servers'] = {
          'main' => {
            'label' => 'XPI',
            'host' => '192.168.1.10',
            'port' => 389,
            'uid' => 'uid',
            'encryption' => 'plain',
            'verify_certificates' => false,
            'bind_dn' => 'uid=admin,cn=users,cn=accounts,dc=cspts,dc=xpi',
            'password' => 'TODO',
            'base' => 'cn=users,cn=accounts,dc=cspts,dc=xpi',
            'attributes' => {
              'username' => ['uid'],
              'name' => ['cn, displayName'],
              'email' => ['mail']
            }
          }
        }
      LOG4J_FORMAT_MSG_NO_LOOKUPS: "true"
    volumes:
      - '/srv/gitlab/config:/etc/gitlab'
      - '/srv/gitlab/logs:/var/log/gitlab'
      - '/srv/gitlab/data:/var/opt/gitlab'
    mac_address: ee:ee:ee:ee:ee:e6
    networks: 
      dockernet:
      xpi:
        ipv4_address: 192.168.1.8


networks:
  dockernet:
    ipam:
      config:
        - subnet: 172.18.0.0/16
          gateway: 172.18.0.1
          ip_range: 172.18.0.0/16
  xpi:
    driver: macvlan
    driver_opts:
      parent: enp1s0
    ipam:
      config:
        - subnet: 192.168.1.0/24
          gateway: 192.168.1.1
          ip_range: 192.168.1.0/28
