FROM jumanjiman/tftp-hpa:latest

COPY health.sh /health.sh

RUN chmod +x /health.sh

HEALTHCHECK CMD /health.sh

ENTRYPOINT ["/usr/sbin/start"]
CMD ["-L", "--verbose", "-m", "/tftpboot/mapfile", "-u", "tftp", "--secure", "/tftpboot"]