version: "3.8"
services:
  ipa:
    image: freeipa/freeipa-server:centos-8
    networks: 
      dockernet:
      xpi:
        ipv4_address: 10.0.1.10
    mac_address: ee:ee:ee:ee:ee:e0
    hostname: ipa.example.test
    tty: true
    stdin_open: true
    read_only: false
    volumes: 
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /var/lib/ipa-data:/data:Z
    sysctls:
      net.ipv6.conf.all.disable_ipv6: 0
    command: --unattended
    ports: 
      - "8001:80"
      - "8444:443"
    environment: 
      IPA_SERVER_INSTALL_OPTS: >
        --ds-password=example123 
        --admin-password=example123 
        --domain=example.test 
        --realm=example.test 
        --setup-dns 
        --forwarder=8.8.8.8  
        --forwarder=8.8.4.4 
        --ntp-server=10.0.1.11
      IPA_SERVER_HOSTNAME: ipa.example.test
  ntp:
    image: atlasplatform/ntp-isolated:latest
    networks: 
      dockernet:
      xpi:
        ipv4_address: 10.0.1.11
    ports:
      - "123:123"

networks:
  dockernet:
  xpi:
    ipam:
      config:
        - subnet: 10.0.1.0/24
          gateway: 10.0.1.1
          ip_range: 10.0.1.0/28